// Generated by ts-to-zod
import { z } from "zod";

export const userSchema = z.object({
    _id: z.string(),
    username: z.string(),
    user_description: z.string().optional(),
    user_tags: z.array(z.string()).optional(),
    github_account_link: z.string().optional(),
    following: z.array(z.number()),
    followed_by: z.array(z.number()),
    follower_count: z.number(),
    authored_ideas: z.array(z.number()),
    owned_projects: z.array(z.number()),
    watched_projects: z.array(z.number()),
    createdAt: z.date(),
    updatedAt: z.date()
});

export const newUserSchema = z.object({
    username: z.string(),
    user_description: z.string().optional(),
    user_tags: z.array(z.string()).optional(),
    github_account_link: z.string().optional()
});
