# Testing user data fetching endpoint:
# GET /api/db/user?id=USER_ID

# Correct request
GET http://localhost:3000/api/db/idea/1

###

# Bad request, no such idea_id
GET http://localhost:3000/api/db/idea/-1

###

# Bad request, wrong request parameter type
GET http://localhost:3000/api/db/idea/abc

###

# Bad request, missing request parameter
GET http://localhost:3000/api/db/idea

###

# Bad request, missing url parameter 
GET http://localhost:3000/api/db/idea?id=