// Generated by ts-to-zod
import { z } from "zod";

export const newUserSchema = z.object({
    //required
    username: z.string().min(3).max(18),
    //optional
    user_description: z.string().max(120).optional(),
    user_tags: z.string().array().max(12).optional(),
    github_account_link: z.string().startsWith("https://github.com/").optional()

});

export const userSchema = newUserSchema.extend({
    _id: z.string(),
    following: z.array(z.number()),
    followed_by: z.array(z.number()),
    follower_count: z.number().min(0),
    authored_ideas: z.array(z.number()).min(0),
    owned_projects: z.array(z.number()).min(0),
    watched_projects: z.array(z.number()).min(0),
    createdAt: z.date(),
    updatedAt: z.date()
});

export type INewUserSchema = z.input<typeof newUserSchema>
